sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
      endpoint: oss-cn-beijing.aliyuncs.com
      access-key-id: LTAI5tMNz8JiAJwZbiBznnfw
      access-key-secret: wrchKQ7O5OdJEqOm2JaH0jkxeByXnY
      bucket-name: namei-sky-take-out

  redis:
    host: localhost
    port: 6379
    database: 0
